services:
  app:
    image: ghcr.io/anhln-embedded/embedded-lab-web:latest
    container_name: embedded_lab_web
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_ENV=production
      - DATABASE_URL=file:/app/prisma/dev.db
    volumes:
      - lab_db_data:/app/prisma
      - lab_uploads_data:/app/public/uploads
    networks:
      - lab_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: embedded_lab_cloudflared
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./.cloudflared:/etc/cloudflared
    networks:
      - lab_network
    depends_on:
      - app

volumes:
  lab_db_data:
    driver: local
  lab_uploads_data:
    driver: local

networks:
  lab_network:
    driver: bridge
