name: CD Pipeline (Production Deployment)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Checkout source code
        uses: actions/checkout@v4

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4

      - name: 🟢 Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: 📥 Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: 🗄️ Generate Prisma Client
        run: pnpm prisma generate
        env:
          DATABASE_URL: "file:./dev.db"

      - name: 🏗️ Next.js Production Build
        run: pnpm build
        env:
          NEXT_PUBLIC_APP_ENV: production
          NEXT_PUBLIC_SITE_URL: https://embedded-aiot.ptit.edu.vn
          DATABASE_URL: "file:./dev.db"
